### ISSUE TITLE
Automatically determine the current project

### ISSUE THREAD

**Issue by matt-allan** [matt-allan/hours#12]
The `add` and `start` commands currently require a `project` argument.  It would be really helpful if the project name could be automatically determined.  There are a few ways we could do this.

**Default project:** Some users may only be tracking time for a single project and they don't want to have to specify it every time.  For this scenario we could allow the user to specify a `default_project` in their config file.  If the project name is not specified the default is used.

**Current directory:** Some users may want to track time based on the current directory.  For example, my `blog` is in the `blog` folder - when I want to track time for the blog I can just execute `hours start` from that folder and it will start tracking time for the blog.

**Dotfile:** Another option is using a dotfile named `.hours` which contains the project name.  If the current working directory has ` .hours` dotfile we read the project name from that.

Some of these rules can't be ran at the same time without some kind of priority - if you have a default do we use that or the current directory?  This could be configurable but maybe we should just decide on a default priority and use that.

**Comment by itsjeffro** [comment]
Hi Matt,

I just wanted to say great ideas. 

The 2nd option sounds like it would be good as a default. Then once a dot file is provided, should take precedence over the default.

**Comment by matt-allan** [comment]
Hey @itsjeffro 👋 , thanks for reading.

Yeah, I like that idea a lot.

If we wanted to add the ability to specify a default project I guess that would need to take priority over the directory, so the order would be:

1.) dotfile
2.) default
3.) current directory

?

I would be happy with just the first two options for now though; should cover 90% of the use cases.

**Comment by matt-allan** [comment]
Thanks again @Douglasdc3, going to close this.
