### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by szepeviktor** [matt-allan/hours#15]
Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Illuminate\Config\Repository' not found in vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:36

my .env file is only `DB_DATABASE=hours.sqlite`

the trick is `Illuminate\Config\Repository` does exist

Could you help?

**Comment by szepeviktor** [comment]
maybe something is not registered in bootstrap/app.php ...

**Comment by matt-allan** [comment]
Hello,

This app doesn't load `.env` at the moment.  You shouldn't need to create that.

That being said, I'm not sure why you are getting that error.  What command are you running when you receive that error?  Could you paste the console command and the output?

> maybe something is not registered in bootstrap/app.php ...

The config class is being instantiated directly in that file, it's not going through a service provider.  It should work as long as `composer` can autoload the file.

**Comment by szepeviktor** [comment]
`php ./hours list`

**Comment by matt-allan** [comment]
Did you already run `composer install`?  Could you try running `composer dump` and then running the command again?

**Comment by szepeviktor** [comment]
of course

strange:

```
$ grep -rFn 'Config\\Repository' vendor/composer/
vendor/composer/autoload_classmap.php:192:    'Illuminate\\Contracts\\Config\\Repository' => $vendorDir . '/illuminate/contracts/Config/Repository.php',
vendor/composer/autoload_static.php:468:        'Illuminate\\Contracts\\Config\\Repository' => __DIR__ . '/..' . '/illuminate/contracts/Config/Repository.php',
```

**Comment by matt-allan** [comment]
🤦‍♂  I did a find and replace with PHPStorm and I guess it edited the `composer.lock`.  I will push a fix.  Sorry about that.

https://github.com/matt-allan/hours/commit/79143ab77b05c46b0be80f891d9b703e3ae173a8#diff-1da2c7edc898c70e5a79a9997c98ceccL300

**Comment by matt-allan** [comment]
Should be fixed by https://github.com/matt-allan/hours/commit/da0b69ee6eb15b4d33071f6b2390fed09b566438.

**Comment by szepeviktor** [comment]
Fixed in https://github.com/matt-allan/hours/commit/da0b69ee6eb15b4d33071f6b2390fed09b566438

Thank you.
