### ISSUE TITLE
Allow including open frames in the report

### ISSUE THREAD

**Issue by matt-allan** [matt-allan/hours#28]
When I'm trying to hit a target i.e. 20 hours per week I will check the report during the day to see how many hours I have left.

```
$ hours report -f 'this week'
```

However the report doesn't include the hours I have put in today on my open frame so I either need to check `hours status` and manually do the math or close the frame and run the report before restarting the frame.

It would be nice if there was a flag on the report command so you could include open frames i.e. `hours report -f 'this week' --with-open-frames`. The report would show `elapsed` time from the start to now and the end time would be empty. The total would include the elapsed time of the open frame.

**Comment by Douglasdc3** [comment]
Given PR #30 is implemented this issue can be closed.

**Comment by matt-allan** [comment]
Thanks @Douglasdc3!
